apiVersion: v1
kind: ConfigMap
metadata:
  name: group-rpc-server-start-config
data:
  discovery.yml: |
    serviceBinaries:
      openim-rpc-group: 1
    toolBinaries:
      - check-free-memory
      - check-component
      - seq
    maxFileDescriptors: 10000