apiVersion: apps/v1
kind: Deployment
metadata:
  name: openim-crontask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crontask
  template:
    metadata:
      labels:
        app: crontask
    spec:
      containers:
        - name: crontask-container
          image: openim/openim-crontask:v3.8.3-1
          env:
            - name: CONFIG_PATH
              value: "/config"
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
            - mountPath: /openim-server/start-config.yml
              name: start-config
              subPath: start-config.yml
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
        - name: start-config
          configMap:
            name: openim-crontask-start-config
