apiVersion: v1
kind: ConfigMap
metadata:
  name: openim-crontask-start-config
data:
  discovery.yml: |
    serviceBinaries:
      openim-crontask: 1
    toolBinaries:
      - check-free-memory
      - check-component
      - seq
    maxFileDescriptors: 10000